# Makefile for dungeon
NAME = vmode
DESCRIPTION = "vmode"
COMPRESSED = NO

# Where to install the program
BINDIR = dist

SRCDIR=.
LIBS =
TERMFLAG =
CFLAGS = -v -Wall -Wextra -Oz
include $(shell cedev-config --makefile)
